### ISSUE TITLE
Not compiling for the latest versions of React Native

### ISSUE THREAD

**Issue by LucasMonteiro1** [FormidableLabs/react-native-controlled-listview#1]
https://github.com/FormidableLabs/react-native-controlled-listview/blob/32508daf224a60b2bbee32b66a2929b1aedc18d6/lib/controlled-list-view.js#L1
  
Change to: 
```javascript
import PropTypes from 'prop-types';
```

**Comment by LucasMonteiro1** [comment]
Submited PR #2

**Comment by jevakallio** [comment]
Closed by #2, thanks @LucasMonteiro1! Released to npm as `react-native-controlled-listview@0.2.0` 🎉
